/* eslint-disable @typescript-eslint/ban-ts-comment */
//! Do not edit this file manually, it is generate by `prisma repo generator`

import { PrismaClient, Prisma, User,
 Post,
 Comment,
 Tag, } from '@prisma/client';
import _ from 'lodash';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyRecord = Record<string, any>;

export type BaseOption<Include, Select> = {
  include?: Include;
  select?: Select;
};

export type Find<Select, Include, Cursor, Order, Distinct> = BaseOption<Include, Select> & {
  cursor?: Cursor;
  take?: number;
  skip?: number;
  orderBy?: Prisma.Enumerable<Order>;
  distinct?: Distinct;
};

export type CountArgs<Select, Cursor, Order, Distinct> = Omit<
  Find<Select, never, Cursor, Order, Distinct>,
  'include'
>;

export type Aggregate<Cursor, Order, Distinct> = Omit<
  CountArgs<never, Cursor, Order, Distinct>,
  'select' | 'distinct'
>;

export const prisma = new PrismaClient({
  log: ['error', 'info', 'query', 'warn'],
});

export const models = _.omit(prisma, [
  '$on',
  '$connect',
  '$disconnect',
  '$use',
  '$executeRaw',
  '$executeRawUnsafe',
  '$queryRaw',
  '$queryRawUnsafe',
  '$transaction',
]);

export const MODELS_NAME = {
  USER: 'user',
  POST: 'post',
  COMMENT: 'comment',
  TAG: 'tag',
} as const;

// eslint-disable-next-line @typescript-eslint/ban-types
export type ModelStructure = {
  user: User;
  post: Post;
  comment: Comment;
  tag: Tag;
};

export type ModelName = keyof ModelStructure;

export type ModelScalarFields<T extends keyof ModelStructure> = Prisma.Enumerable<
  keyof ModelStructure[T]
>;

export type ModelDelegate = Prisma.RejectOnNotFound | Prisma.RejectPerOperation | undefined;

export type ModelTypes<T = unknown> = {
  user: {
    Where: Prisma.UserWhereInput;
    Select: Prisma.UserSelect;
    Include: unknown;
    Create: Prisma.UserCreateInput | Prisma.UserUncheckedCreateInput;
    Update: Prisma.UserUpdateInput | Prisma.UserUncheckedUpdateInput;
    Cursor: Prisma.UserWhereUniqueInput;
    Order: Prisma.UserOrderByWithRelationInput;
    Delegate: Prisma.UserDelegate<ModelDelegate>;
    GroupBy: Prisma.UserGroupByOutputType;
    // @ts-ignore
    Return: Prisma.UserGetPayload<T>;
  },
  post: {
    Where: Prisma.PostWhereInput;
    Select: Prisma.PostSelect;
    Include: Prisma.PostInclude;
    Create: Prisma.PostCreateInput | Prisma.PostUncheckedCreateInput;
    Update: Prisma.PostUpdateInput | Prisma.PostUncheckedUpdateInput;
    Cursor: unknown;
    Order: Prisma.PostOrderByWithRelationInput;
    Delegate: Prisma.PostDelegate<ModelDelegate>;
    GroupBy: Prisma.PostGroupByOutputType;
    // @ts-ignore
    Return: Prisma.PostGetPayload<T>;
  },
  comment: {
    Where: Prisma.CommentWhereInput;
    Select: Prisma.CommentSelect;
    Include: Prisma.CommentInclude;
    Create: Prisma.CommentCreateInput | Prisma.CommentUncheckedCreateInput;
    Update: Prisma.CommentUpdateInput | Prisma.CommentUncheckedUpdateInput;
    Cursor: unknown;
    Order: Prisma.CommentOrderByWithRelationInput;
    Delegate: Prisma.CommentDelegate<ModelDelegate>;
    GroupBy: Prisma.CommentGroupByOutputType;
    // @ts-ignore
    Return: Prisma.CommentGetPayload<T>;
  },
  tag: {
    Where: Prisma.TagWhereInput;
    Select: Prisma.TagSelect;
    Include: unknown;
    Create: Prisma.TagCreateInput | Prisma.TagUncheckedCreateInput;
    Update: Prisma.TagUpdateInput | Prisma.TagUncheckedUpdateInput;
    Cursor: Prisma.TagWhereUniqueInput;
    Order: Prisma.TagOrderByWithRelationInput;
    Delegate: Prisma.TagDelegate<ModelDelegate>;
    GroupBy: Prisma.TagGroupByOutputType;
    // @ts-ignore
    Return: Prisma.TagGetPayload<T>;
  },
};
