import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/shared/Navbar';
import StoreProvider from './StoreProvider';
import { Toaster } from '@/components/ui/toaster';
import { useToast } from '@/components/ui/use-toast';
import { ToastContextProvider } from '../../contexts/toast.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex h-screen flex-col ${inter.className}`}>
        <StoreProvider>
          <ToastContextProvider>
            <Navbar />
            <div className="mt-10">{children}</div>
            <Toaster />
          </ToastContextProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
