import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';
import { Toaster } from '@/components/ui/toaster';
import { ToastContextProvider } from '../../contexts/toast.context';
import { ThemeProvider } from 'next-themes';
import { SessionWrapper } from '../../contexts/auth.context';
import Navbar from '@/components/shared/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`flex h-screen flex-col ${inter.className} dark:bg-[#0D1117]`}
      >
        <StoreProvider>
          <SessionWrapper>
            <ToastContextProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem={true}
              >
                <Navbar />
                <div className="mt-10">{children}</div>
                <Toaster />
              </ThemeProvider>
            </ToastContextProvider>
          </SessionWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
